### ISSUE TITLE
Use custom format instead of the default

### ISSUE THREAD

**Issue by pavlospt** [f2prateek/gradle-android-javafmt-plugin#1]
Hello, 

Thank you for open sourcing it. Is it possible to change the format to a custom one ?

**Comment by f2prateek** [comment]
Google Java Format only supports two styles (Google and AOSP  https://github.com/google/google-java-format/blob/28937f96465324d8bcaff3514db4212dfd388207/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L46-L50).

I won't get around to adding AOSP style support, but open to accepting a PR.

Beyond that there are no plans to support custom formats. The whole point is to not have custom styles and not have developers waste time arguing over tabs vs spaces.
