### ISSUE TITLE
exclude build folders (?)

### ISSUE THREAD

**Issue by kaushikgopal** [f2prateek/gradle-android-javafmt-plugin#11]
when i run `checkFmt` i get an error code violation
```
expected at line 10:
  public static final class permission {
    public static final String C2D_MESSAGE =
        "com.my.app.dev.permission.C2D_MESSAGE";
  }
got at line 10:
    public static final class permission {
        public static final String C2D_MESSAGE="com.my.app.permission.C2D_MESSAGE";
    }
```

running  `./gradlew fmt` does not correct this.

i'm guessing we'll have to not include build generated files in the checker?

the file in question is the `Manifest.java` file present in the build folder

**Comment by f2prateek** [comment]
Yep this sounds like a bug. We should definitely exclude build generated folders in the formatter and checker.

Slightly surprised `./gradlew fmt` doesn't fix it because it they depend on the same source set.
