### ISSUE TITLE
running gradlew build does not fail

### ISSUE THREAD

**Issue by gabrielittner** [f2prateek/gradle-android-javafmt-plugin#19]
Reproduction steps:
1. Change something so that your code is not formatted properly
2. Run ./gradlew checkFmt
3. Run ./gradlew build 

The execution in 2 fails because there are formatting errors, 3 does not fail. This is because the `fmt` is executed as part of assemble which is run before the `check` tasks.

**Comment by f2prateek** [comment]
Hmm, I do want 3 to not fail during development, and just do the right thing and format your code. But I can see people expecting it to fail on CI. Not sure what's less surprising.

**Comment by f2prateek** [comment]
Maybe we have to give up on the idea of it working automagically, and make folks run `fmt` manually.

**Comment by gabrielittner** [comment]
We could add a new extension property which determines whether `assemble` depends on `fmt`. So you could do something like:

```groovy
javafmt {
  formatWhenBuilding !isRunningOnCi
}
```

**Comment by gabrielittner** [comment]
Do you want a pr for this?

**Comment by f2prateek** [comment]
hey @gabrielittner; sorry for the delay here. I think if we added an option `formatOnAssemble`; that would be good.

Alternatively, we can make `assemble` not depend on `fmt` at all.
