### ISSUE TITLE
Take product flavors into account

### ISSUE THREAD

**Issue by mannodermaus** [f2prateek/gradle-android-javafmt-plugin#2]
Currently, the plugin doesn't take projects with multiple `productFlavors` into account, and causes a conflict in the task graph: "a task with that name already exists". Instead of using [the build type's name alone](https://github.com/f2prateek/gradle-android-javafmt-plugin/blob/master/src/main/groovy/com/f2prateek/javafmt/AndroidJavafmtPlugin.groovy#L24), the variant's flavor name should be used, since it provides a more unique identifier that also contains the build type.

I'm going to send a PR that fixes this shortly.

**Comment by f2prateek** [comment]
Closed by #3
