### ISSUE TITLE
Add AOSP option (4 space indent)

### ISSUE THREAD

**Issue by gabrielittner** [f2prateek/gradle-android-javafmt-plugin#9]
For reference: https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L40

**Comment by f2prateek** [comment]
related https://github.com/f2prateek/gradle-android-javafmt-plugin/issues/1#issuecomment-283195189

**Comment by gabrielittner** [comment]
Sorry missed that. I'll open a pr within the next days. Do you also want one for #4?

**Comment by f2prateek** [comment]
Sure! I've been putting it off for until the next javaformat release but it'd definitely be helpful to have it ready before then 🙏

**Comment by f2prateek** [comment]
Closed by #15
